- name: Test Docker container creation
  hosts: docker-vm
  tasks:
    - name: Run the Docker bulid
      shell: docker-compose build --no-cache
      

    - name: Run the Docker container
      shell: docker-compose up -d
      
